### ISSUE TITLE
Error when running init_avo codegen file.

### ISSUE THREAD

**Issue by magtastic** [avohq/avo#134]
## Version:
```bash
 avo --version
3.2.2
```
## Description:
I just pulled via avo-cli and it changed the implementation of `init_avo` method in the generated file.
Before it was:
```python
            if "apiKey" in inspect.getfullargspec(global_amplitude.make).args:
```
Now:
```python
            if "apiKey" in inspect.getargspec(global_amplitude.make).args:
```

This causes the method to raise this error:
```bash
Traceback (most recent call last):
  File "/Users/magtastic/.config/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/magtastic/.config/.pyenv/versions/3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/magtastic/Developer/Smitten/api/server/server.py", line 44, in <module>
    avo.init_avo(
  File "/Users/magtastic/Developer/Smitten/api/server/core/avo.py", line 269, in init_avo
    if "apiKey" in inspect.getargspec(global_amplitude.make).args:
  File "/Users/magtastic/.config/.pyenv/versions/3.10.4/lib/python3.10/inspect.py", line 1245, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them
make[1]: *** [run_server] Error 1
```
If I manually edit the generated file to use the older `getfullargspec` method, everything works fine.

How I call the method:
```python
amplitude_destination = AmplitudeDestination()
AVO_ENV = "prod" if APP_CONFIG.get("ENVIRONMENT", None) == "prod" else "dev"
avo.init_avo(
    options={"env": AVO_ENV, "strict": True, "verbose": True},
    amplitude=amplitude_destination,
)
```

Did this change recently?

**Comment by magtastic** [comment]
Works on my end! Thanks for the quick fix
